# This profile disables messaging (AMQP bus, RabbitMQ auto-discovery, RabbitMQ health indicator).
# It is used for development when someone wants to run locally without RabbitMQ support

spring:
  cloud:
    bus:
      enabled: false
  rabbitmq:
    discovery:
      enabled: false

management:
  health:
    rabbit:
      enabled: false
