# Authorization requires a client certificate
server:
  ssl:
    client-auth: NEED

query:
  storage:
    sendNotifications: true
    syncStorage: true
    backend: RABBITMQ

logging:
  level:
    datawave.microservice.common.storage: DEBUG